CREATE TABLE vsfootball.user (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Created BIGINT NOT NULL,Updated BIGINT NOT NULL, Guid CHAR(32) NOT NULL UNIQUE, Firstname VARCHAR(50),Lastname VARCHAR(50), Username VARCHAR(100) NOT NULL UNIQUE, Password VARCHAR(50),Accounttype VARCHAR(100),Accesstoken VARCHAR(255), Tokenexpiration VARCHAR(100), Verified INT,Playsowned VARCHAR(255),Platform VARCHAR(100),Androiddevices VARCHAR(255),Iosdevices VARCHAR(255),PRIMARY KEY (Id));
CREATE TABLE vsfootball.feedback (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Created BIGINT NOT NULL, Userid CHAR(32) NOT NULL,Comment VARCHAR(255) NOT NULL, Gameid VARCHAR(100), Screen VARCHAR(100),Os VARCHAR(10), PRIMARY KEY (Id));
CREATE TABLE vsfootball.game(Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Created BIGINT NOT NULL, Player1 CHAR(32) NOT NULL, Player2 CHAR(32) NOT NULL, Player1teamname VARCHAR(30), Player2teamname VARCHAR(30), Outcome VARCHAR(50), Player1accepteddate BIGINT , Player2accepteddate BIGINT, Enddate BIGINT, Inviteaccepted INT,Lastupdated BIGINT,Player1prefix VARCHAR(30),Player2prefix VARCHAR(30), PRIMARY KEY(Id) );
CREATE TABLE vsfootball.turn(Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Gameid BIGINT NOT NULL,Player1id CHAR(32) NOT NULL, Player2id CHAR(32) NOT NULL, Previousturn BIGINT, Yardline INT NOT NULL, Down INT ,Downdistance Int,Player1playselected INT , Player2playselected INT, Player1role INT NOT NULL, Player2role INT NOT NULL, Results VARCHAR(200), Playtime INT, Timeelapsedingame INT, Currentplayer1score INT NOT NULL, Currentplayer2score INT NOT NULL,Player1playdatetime BIGINT,Player2playdatetime BIGINT,Player1playflipped INT NOT NULL, Player2playflipped INT NOT NULL,Animationforturn VARCHAR(50), PRIMARY KEY(Id));
CREATE TABLE vsfootball.play (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Title VARCHAR(50),Image VARCHAR(255),Type VARCHAR(255),Possession INT,Premium INT, Productid VARCHAR(255),Producttype INT,Price FLOAT, Canflip INT, Version INT,Filesize DOUBLE,Description VARCHAR(100), PRIMARY KEY (Id));
CREATE TABLE vsfootball.animation(Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Image VARCHAR(255), Tier INT, Frames FLOAT,Framespersecond FLOAT,Category VARCHAR(30), Version INT, Filesize DOUBLE, PRIMARY KEY (Id));
CREATE TABLE vsfootball.androiddevice (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Deviceid VARCHAR(255) UNIQUE, PRIMARY KEY(Id));
CREATE TABLE vsfootball.iosdevice (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Devicetoken VARCHAR(255) UNIQUE, PRIMARY KEY(Id));
CREATE TABLE vsfootball.storepurchase (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Userid CHAR(32) NOT NULL,Productid VARCHAR(255),Playid BIGINT, Receipt VARCHAR(3000),Os VARCHAR(10), PRIMARY KEY(Id));
CREATE TABLE vsfootball.chatmessage (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Sender CHAR(32) NOT NULL,Senderteamname VARCHAR(10) NOT NULL, Gameid BIGINT NOT NULL, Created BIGINT NOT NULL, Message VARCHAR(140), PRIMARY KEY(Id));
CREATE TABLE vsfootball.usergamelookup (Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT, Userid CHAR(32) NOT NULL,Gameid BIGINT NOT NULL, PRIMARY KEY(Id));
ALTER TABLE vsfootball.usergamelookup ADD CONSTRAINT fk_user_lookup FOREIGN KEY(Userid) REFERENCES vsfootball.user(Guid);
ALTER TABLE vsfootball.usergamelookup ADD CONSTRAINT fk_game_lookup FOREIGN KEY(Gameid) REFERENCES vsfootball.game(Id);
ALTER TABLE vsfootball.turn ADD CONSTRAINT fk_game_turns  FOREIGN KEY (Gameid) REFERENCES vsfootball.game(Id);  
ALTER TABLE vsfootball.feedback ADD CONSTRAINT fk_user_feedback FOREIGN KEY (Userid) REFERENCES vsfootball.user(Guid);
ALTER TABLE vsfootball.storepurchase ADD CONSTRAINT fk_user_purchase FOREIGN KEY (Userid) REFERENCES vsfootball.user(Guid);
ALTER TABLE vsfootball.storepurchase ADD CONSTRAINT fk_play_purchase FOREIGN KEY (Playid) REFERENCES vsfootball.play(Id);
ALTER TABLE vsfootball.chatmessage ADD CONSTRAINT fk_user_chatmessage FOREIGN KEY (Sender) REFERENCES vsfootball.user(Guid);
ALTER TABLE vsfootball.chatmessage ADD CONSTRAINT fk_game_chatmessage FOREIGN KEY (Gameid) REFERENCES vsfootball.game(Id);


INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Lead Dive','1.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Off-Tackle','2.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Lead Toss Sweep','3.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Counter Trey','4.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Toss Power Trap','5.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Draw','6.png','Run','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Screen','7.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('FB Loop','8.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('X Slant','9.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Z Fly','10.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Play Action, TE Seem','11.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('QB Bootleg Option','12.png','Pass','0','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Kickoff','13.png','ST-K','4','0','',1,0,0,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('OnsIde Kick','14.png','ST-K','4','0','',1,0,0,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Punt','15.png','ST-O','2','0','',1,0,0,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Fake Punt','16.png','ST-O','2','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Fake Dive Z Toss Reverse','17.png','Run','0','1','vsfplay17',1,0.99,1,2,0,'17.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('HB Pass','18.png','Pass','0','1','vsfplay18',1,0.99,1,2,0,'18.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Pistol Fake Rev Vert Pass','19.png','Pass','0','1','vsfplay19',1,0.99,1,2,0,'19.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Pistol Z Reverse','20.png','Run','0','1','vsfplay20',1,0.99,1,2,0,'20.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Pistol Inside Read Option','21.png','Run','0','1','vsfplay21',1,0.99,1,2,0,'21.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Pistol Play Action Pass','22.png','Pass','0','1','vsfplay22',1,0.99,1,2,0,'22.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Hail Mary','23.png','Pass','0','1','vsfplay23',1,0.99,1,2,0,'23.html');

INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('4-3 Cover 2','24.png','Run','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('4-3 Quarters Zone','25.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('4-3 Crash Blitz','26.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('4-3 SS Blitz','27.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('4-3 Corner Blitz','28.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('2-5 Eagle','29.png','Run','1','0','',1,0,0,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('44 Stack','30.png','Run','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Nickel','31.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Dime','32.png','Pass','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('3-4 Base','33.png','Run','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('3-4 Prevent','34.png','Run','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('46 Defense','35.png','Run','1','1','vsfplay35',1,0.99,1,2,0,'35.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Goal Line','36.png','Run','1','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Kickoff Return','37.png','ST-KR','5','0','',1,0,0,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Hands Team','38.png','ST-KR','5','1','vsfplay38',1,0.99,1,2,0,'38.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Homerun Throwback','39.png','ST-KR','5','1','vsfplay39',1,0.99,1,2,0,'39.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Punt Return','40.png','ST-D','3','0','',1,0,1,2,0,'');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Punt Block','41.png','ST-D','3','1','vsfplay41',1,0.99,1,2,0,'41.html');
INSERT INTO vsfootball.play(Title,Image,Type,Possession,Premium,Productid,Producttype,Price,Canflip,Version,Filesize,Description) VALUES ('Field Goal','42.png','ST-O','2','0','',1,0,0,2,0,'');

INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('100Snap.gif',100,10,10,'snap',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('200HandoffShortRun.gif',200,12,10,'run',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('201QBPass.gif',201,11,10,'pass',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('300LongRun.gif',300,17,10,'long-run',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('301LongPass.gif',301,14,10,'long-pass',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('400Catch.gif',400,11,10,'complete',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('401Incomplete.gif',401,12,10,'incomplete',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('402Interception.gif',402,11,10,'interception',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('403Fumble.gif',403,10,10,'fumble',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('500Tackle.gif',500,11,10,'tackle',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('501TD.gif',501,28,10,'touchdown',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('502TDDef.gif',501,28,10,'touchdown',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('501TDaFeet.gif',501,9,10,'touchdowna',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('501TDbRef.gif',501,9,10,'touchdownb',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('501TDcSpike.gif',501,10,10,'touchdownc',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('502DefTDaFeet.gif',501,9,10,'deftouchdowna',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('502DefTDbRef.gif',501,9,10,'deftouchdownb',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('502DefTDcSpike.gif',501,10,10,'deftouchdownc',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('101Kickoff.gif',101,13,10,'kickoff',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('600GameOverA.gif',600,10,10,'gameovera',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('600GameOverB.gif',600,19,10,'gameoverb',2,0);
INSERT INTO vsfootball.animation(Image,Tier,Frames,Framespersecond,Category,Version,Filesize) VALUES ('RandomOpponent.gif',1000,2,1,'randomopponent',1,0);